add steps to sync renovate configs

diff --git a/.github/workflows/sync-renovate-configs.yml b/.github/workflows/sync-renovate-configs.yml
--- a/.github/workflows/sync-renovate-configs.yml
+++ b/.github/workflows/sync-renovate-configs.yml
@@ -108,6 +108,23 @@ jobs:
           ls -lrt renovate-central
           ls -lrt target-repo
 
+      - name: Sync renovate.json
+        run: mv renovate-central/${{ matrix.config.renovate-config }} target-repo/${{ matrix.config.targetFilePath }}
+
+      - name: Commit Changes
+        run: |
+          cd target-repo
+          git status
+
+          # Exit if any file other than renovate.json is modified
+          git status --porcelain | egrep -v '^\s?M\s\${{ matrix.config.targetFilePath }}' && echo "Error: Files other than renovate.json are modified" && exit 1
+          
+          echo "Adding and committing the changes..."
+          git add ${{ matrix.config.targetFilePath }}
+          git status --porcelain
+          git commit -m "sync config with renovate-central"
+          # git push origin main
+
       # - name: Slack Notification
       #   if: ${{ failure() }}
       #   uses: rtCamp/action-slack-notify@v2
